import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';

await test('setup protects private files without breaking access and preserves existing secrets', t => {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), 'rdcx-setup-'));
  t.after(() => fs.rmSync(base, { recursive: true, force: true }));
  fs.mkdirSync(path.join(base, 'scripts'));
  const script = path.join(base, 'scripts', 'setup.mjs');
  fs.copyFileSync(new URL('../scripts/setup.mjs', import.meta.url), script);
  const run = () => spawnSync(process.execPath, [script], { encoding: 'utf8', windowsHide: true, timeout: 15000 });
  const first = run(); assert.equal(first.status, 0, first.stderr);
  const configPath = path.join(base, '.rdc', 'config.json');
  const keyPath = path.join(base, '.rdc', 'admin-token.txt');
  const config = fs.readFileSync(configPath, 'utf8'); const key = fs.readFileSync(keyPath, 'utf8');
  const firstConfig = JSON.parse(config);
  assert.equal(firstConfig.terminalEnabled, true);
  assert.equal(firstConfig.systemProcessControlEnabled, true);
  assert.equal(firstConfig.desktopControlEnabled, true);
  assert.equal(firstConfig.networkFetchEnabled, true);
  assert.equal(firstConfig.requireWriteApproval, true);
  assert.equal(firstConfig.policyDefaultsApplied, true);
  assert.equal(JSON.parse(config).roots[0].path, path.join(base, 'workspace'));
  assert.equal(key.length, 43);
  const second = run(); assert.equal(second.status, 0, second.stderr);
  assert.equal(fs.readFileSync(configPath, 'utf8'), config);
  assert.equal(fs.readFileSync(keyPath, 'utf8'), key);

  const movedConfig = JSON.parse(config);
  const staleParent = path.join(path.dirname(base), path.basename(base).replace(/-/g, '_'));
  movedConfig.roots = [{ path: path.join(staleParent, 'workspace'), write: true }];
  fs.writeFileSync(configPath, JSON.stringify(movedConfig, null, 2));
  const migrated = run(); assert.equal(migrated.status, 0, migrated.stderr);
  const migratedConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  assert.equal(migratedConfig.roots[0].path, path.join(base, 'workspace'));
  assert.match(migrated.stdout, /Migrating default workspace root:/);
  assert.equal(fs.readFileSync(keyPath, 'utf8'), key);
});
